<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mobile_robot_controller</name>
  <version>1.0.0</version>
  <description>Unified Controller Stack: Custom Kinematics, ros2_control &amp; Teleop for 4-wheel mobile robot.</description>
  <maintainer email="rahul.r.joshua123@gmail.com">Rahul Ramasamy</maintainer>
  <author email="rahul.r.joshua123@gmail.com">Rahul Ramasamy</author>
  <license>Apache-2.0</license>

  <url type="website">https://rahul-r-joshua.github.io/portfolio/</url>
  <url type="repository">https://github.com/rahul-r-joshua/ROS2-Mobile-Robot-Masterclass</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Core Kinematics Dependencies -->
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <!-- Teleop & Multiplexing Dependencies -->
  <depend>joy</depend>
  <depend>teleop_twist_joy</depend>
  <depend>twist_mux</depend>

  <!-- Upstream ros2_control Dependencies -->
  <depend>controller_manager</depend>
  <depend>diff_drive_controller</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>joint_state_publisher</depend>
  <depend>robot_state_publisher</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
