<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mobile_robot_bringup</name>
  <version>1.0.0</version>
  <description>Complete system bringup launch files (Gazebo, Joystick Deadman, Twist Mux, Safety Zone C++ &amp; Python) for 4-wheel robot.</description>
  <maintainer email="rahul.r.joshua123@gmail.com">Rahul Ramasamy</maintainer>
  <author email="rahul.r.joshua123@gmail.com">Rahul Ramasamy</author>
  <license>Apache-2.0</license>

  <url type="website">https://rahul-r-joshua.github.io/portfolio/</url>
  <url type="repository">https://github.com/rahul-r-joshua/ROS2-Mobile-Robot-Masterclass</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>

  <exec_depend>mobile_robot_description</exec_depend>
  <exec_depend>mobile_robot_controller</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>twist_mux</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
